update@20201013

diff --git a/luci-app-openclash/root/etc/init.d/openclash b/luci-app-openclash/root/etc/init.d/openclash
--- a/luci-app-openclash/root/etc/init.d/openclash
+++ b/luci-app-openclash/root/etc/init.d/openclash
@@ -139,16 +139,7 @@ cat "$CHANGE_FILE" "$DNS_FILE" "$PROXY_PROVIDER_FILE" "$PROXY_FILE" "$GROUP_FILE
 
 yml_check()
 {
-   #格式替换
-   sed -i 's/\t/ /g' "$3" 2>/dev/null
-   sed -i "s/- \{2,\}/- /g" "$3" 2>/dev/null
-   sed -i "s/^\.\.\.$//g" "$3" 2>/dev/null
-   sed -i "s/^---$//g" "$3" 2>/dev/null
-   sed -i "s/^ \{1,\}dns:/dns:/g" "$3" 2>/dev/null
-
-   #检查关键字避免后续操作出错
-   /usr/share/openclash/yml_field_name_ch.sh "$3" 2>/dev/null
-
+	
    #创建启动备份
    cp "$3" "$5"
    
@@ -156,6 +147,17 @@ yml_check()
    if [ ! -f "$4" ]; then
       cp "$3" "$4"
    fi
+   
+   #格式替换
+   sed -i 's/\t/ /g' "$3" 2>/dev/null
+   sed -i "s/- \{2,\}/- /g" "$3" 2>/dev/null
+   sed -i "s/^\.\.\.$//g" "$3" 2>/dev/null
+   sed -i "s/^---$//g" "$3" 2>/dev/null
+   sed -i "s/^ \{1,\}dns:/dns:/g" "$3" 2>/dev/null
+   sed -i '/OpenClash-General/d' "$3" 2>/dev/null
+
+   #检查关键字避免后续操作出错
+   /usr/share/openclash/yml_field_name_ch.sh "$3" 2>/dev/null
 
    #取出general部分
    /usr/share/openclash/yml_field_cut.sh "general" "$CHANGE_FILE" "$3"
@@ -303,8 +305,6 @@ EOF
    uci set openclash.config.dns_port="$dns_port" && uci commit openclash
    
    #添加标识
-   sed -i '/OpenClash-General/d' "$DNS_FILE" 2>/dev/null
-   sed -i '/OpenClash-General/d' "$FALLBACK_FILTER_FILE" 2>/dev/null
    echo '#===================== OpenClash-General-Settings =====================#' >> "$FALLBACK_FILTER_FILE" 2>/dev/null
 }
 
@@ -519,7 +519,7 @@ EOF
          sed -i "/ipcidr:/c\    ipcidr:" "$3" 2>/dev/null
       fi
       if [ -z "$(grep "^      - " "$3")" ]; then
-         sed -i '/^ \{0,\}ipcidr:/,/OpenClash-General-Settings/ {s/^ \{0,\}- /      - /}' "$3" 2>/dev/null #修改参数空格
+         sed -i '/^ \{0,\}ipcidr:/,/,$/ {s/^ \{0,\}- /      - /g}' "$3" 2>/dev/null #修改参数空格
       fi
    fi
 
@@ -987,14 +987,14 @@ do_run_file()
 
    if [ "$small_flash_memory" != "1" ]; then
       dev_core_path="/etc/openclash/core/clash"
-   	  tun_core_path="/etc/openclash/core/clash_tun"
-   	  game_core_path="/etc/openclash/core/clash_game"
-   	  geoip_path="/etc/openclash/Country.mmdb"
+      tun_core_path="/etc/openclash/core/clash_tun"
+      game_core_path="/etc/openclash/core/clash_game"
+      geoip_path="/etc/openclash/Country.mmdb"
    else
       dev_core_path="/tmp/etc/openclash/core/clash"
-   	  tun_core_path="/tmp/etc/openclash/core/clash_tun"
-   	  game_core_path="/tmp/etc/openclash/core/clash_game"
-   	  geoip_path="/tmp/etc/openclash/Country.mmdb"
+      tun_core_path="/tmp/etc/openclash/core/clash_tun"
+      game_core_path="/tmp/etc/openclash/core/clash_game"
+      geoip_path="/tmp/etc/openclash/Country.mmdb"
    fi
     
    rm -rf "/etc/openclash/clash" 2>/dev/null
@@ -1044,7 +1044,7 @@ do_run_file()
    [ ! -x "$dev_core_path" ] && chmod 4755 "$dev_core_path" 2>/dev/null
    
    [ -f "$geoip_path" ] && [ "$small_flash_memory" = "1" ] && {
-   	  rm -rf "/etc/openclash/Country.mmdb" 2>/dev/null
+      rm -rf "/etc/openclash/Country.mmdb" 2>/dev/null
       ln -s "$geoip_path" /etc/openclash/Country.mmdb 2>/dev/null
    }
    
@@ -1064,6 +1064,17 @@ do_run_file()
      nohup /usr/share/openclash/openclash_core.sh "$core_type" &
      exit 0
    }
+   
+   if ! capsh --is-uid=0 >/dev/null; then
+     echo "错误：Capsh异常，请尝试重新安装依赖【libcap】和相应的Capsh库，终止启动..." >$START_LOG
+     echo "${LOGTIME} Error: Could Not Load The Capsh Library, Please Verify The Capsh Shell Library Work Well" >> $LOG_FILE
+     echo "${LOGTIME} Tip: You Could Download And Re-Install The libcap & libcap-bin Library From The Address Below:" >> $LOG_FILE
+     echo "" >> $LOG_FILE
+     echo "---------- https://mirrors.cloud.tencent.com/lede/snapshots/packages/ ----------" >> $LOG_FILE
+     echo "" >> $LOG_FILE
+     sleep 5
+     start_fail
+   fi
 
 }
 
@@ -1079,7 +1090,7 @@ start_run_core()
       kill_clash
       #使用nobody启动内核方便代理路由自身流量
       capabilties="cap_sys_resource,cap_dac_override,cap_net_raw,cap_net_bind_service,cap_net_admin"
-      capsh --caps="${capabilties}+eip" -- -c "capsh --user=nobody --addamb='${capabilties}' -- -c 'nohup $CLASH -d $CLASH_CONFIG -f $CONFIG_FILE >> $LOG_FILE 2>&1 &'"
+      capsh --caps="${capabilties}+eip" -- -c "capsh --user=nobody --addamb='${capabilties}' -- -c 'nohup $CLASH -d $CLASH_CONFIG -f \"$CONFIG_FILE\" >> $LOG_FILE 2>&1 &'" >> $LOG_FILE 2>&1
    fi
    uci set openclash.config.config_reload=1 2>/dev/null
    uci commit openclash
@@ -1088,9 +1099,9 @@ start_run_core()
 check_core_status()
 {
    check_time=1
-   while ( [ "$check_time" -le 3 ] && [ -z "$(pidof clash)" ] )
+   while ( [ "$check_time" -le 3 ] && [ -n "$(pidof clash)" ] )
    do
-      sleep 2
+      sleep 1
       check_time=$(expr "$check_time" + 1)
    done
 }
@@ -1163,10 +1174,10 @@ raw_config_start()
    fi
    
    dase=$(grep "^ \{0,\}Secret:" "$CONFIG_FILE" |awk -F ': ' '{print $2}' |awk -F '#' '{print $1}' |sed 's/^ \{0,\}//g' 2>/dev/null |sed 's/ \{0,\}$//g' 2>/dev/null |sed "s/\'//g" 2>/dev/null |sed "s/\'//g" 2>/dev/null)
-   uci set openclash.config.dashboard_password=dase 2>/dev/null
+   uci set openclash.config.dashboard_password="$dase" 2>/dev/null
    
    cn_port=$(grep "^ \{0,\}external-controller:" "$CONFIG_FILE" |awk -F ':' '{print $3}' |awk -F '#' '{print $1}' |tr -cd "[0-9]" 2>/dev/null)
-   uci set openclash.config.dashboard_password=cn_port 2>/dev/null
+   uci set openclash.config.dashboard_password="$cn_port" 2>/dev/null
    
    uci set openclash.config.restricted_mode=1
    
@@ -1232,15 +1243,18 @@ firewall_redirect_exclude()
    if [ -z "$src_dport" ]; then
       return
    fi
-   
-   if [ -z "$en_mode_tun" ]; then
-      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+
+   if [ -z "$en_mode_tun" ] || [ "$en_mode_tun" -eq 3 ]; then
+   	  iptables -t nat -I openclash_output -p tcp --sport "$src_dport" -j RETURN >/dev/null 2>&1
+   	  iptables -t mangle -I openclash_output -p udp --sport "$src_dport" -j RETURN >/dev/null 2>&1
+      iptables -t mangle -I openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
    elif [ "$en_mode_tun" -ne 3 ]; then
-      iptables -t mangle -A openclash -p tcp --dport "$src_dport" -j RETURN >/dev/null 2>&1
-      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
-   else
-      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+   	  iptables -t mangle -I openclash_output -p tcp --sport "$src_dport" -j RETURN >/dev/null 2>&1
+   	  iptables -t mangle -I openclash_output -p udp --sport "$src_dport" -j RETURN >/dev/null 2>&1
+      iptables -t mangle -I openclash -p tcp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+      iptables -t mangle -I openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
    fi
+
 }
 
 set_firewall()
@@ -1381,9 +1395,6 @@ if [ -z "$en_mode_tun" ] || [ "$en_mode_tun" -eq 3 ]; then
             iptables -t mangle -A openclash -m set --match-set china_ip_route dst -j RETURN >/dev/null 2>&1
          fi
          iptables -t mangle -A openclash -p udp --dport 53 -j RETURN >/dev/null 2>&1
-         #端口转发
-         config_load "firewall"
-         config_foreach firewall_redirect_exclude "redirect"
          iptables -t mangle -A openclash -p udp -j TPROXY --on-port "$proxy_port" --on-ip 0.0.0.0 --tproxy-mark "$PROXY_FWMARK"
          iptables -t mangle -A PREROUTING -p udp -j openclash
       fi
@@ -1395,7 +1406,7 @@ if [ -z "$en_mode_tun" ] || [ "$en_mode_tun" -eq 3 ]; then
       iptables -t nat -A openclash_output -m set --match-set localnetwork dst -j RETURN
       #iptables -t nat -A openclash_output -p tcp -d 198.18.0.0/16 -j REDIRECT --to-ports "$proxy_port"
       iptables -t nat -A openclash_output -m owner ! --uid-owner 65534 -p tcp -j REDIRECT --to-ports "$proxy_port"
-      iptables -t nat -A OUTPUT -j openclash_output
+      iptables -t nat -I OUTPUT -j openclash_output
    #fi
 
    #if [ "$ipv6_enable" -eq 1 ]; then
@@ -1446,20 +1457,17 @@ if [ -n "$en_mode_tun" ]; then
    iptables -t mangle -N openclash_output
    iptables -t mangle -F openclash_output
    iptables -t mangle -A openclash_output -m set --match-set localnetwork dst -j RETURN
-   iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -j MARK --set-mark "$PROXY_FWMARK"
    if [ "$en_mode_tun" -ne 3 ]; then
-      iptables -t mangle -I OUTPUT -j openclash_output
+      iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -j MARK --set-mark "$PROXY_FWMARK"
    else
-      iptables -t mangle -I OUTPUT -p udp -j openclash_output
+      iptables -t mangle -A openclash_output -m owner ! --uid-owner 65534 -p udp -j MARK --set-mark "$PROXY_FWMARK"
    fi
+   iptables -t mangle -I OUTPUT -j openclash_output
    
    iptables -t mangle -N openclash
    iptables -t mangle -F openclash
    iptables -t mangle -N openclash_dns_hijack
    iptables -t mangle -F openclash_dns_hijack
-   #端口转发
-   config_load "firewall"
-   config_foreach firewall_redirect_exclude "redirect"
    #其他流量
    iptables -t mangle -A openclash -m set --match-set localnetwork dst -j RETURN >/dev/null 2>&1
    iptables -t mangle -A openclash -m set --match-set wan_ac_black_ips dst -j RETURN >/dev/null 2>&1
@@ -1489,6 +1497,10 @@ if [ -n "$en_mode_tun" ]; then
    #        ip6tables -t mangle -I PREROUTING -j MARK --set-mark "$PROXY_FWMARK"
    #    fi
 fi
+
+#端口转发
+config_load "firewall"
+config_foreach firewall_redirect_exclude "redirect"
 }
 
 revert_firewall()
@@ -1553,7 +1565,6 @@ revert_firewall()
    ip tuntap del clash0 mode tun >/dev/null 2>&1
 
    iptables -t mangle -D OUTPUT -j openclash_output >/dev/null 2>&1
-   iptables -t mangle -D OUTPUT -p udp -j openclash_output >/dev/null 2>&1
    iptables -t mangle -D PREROUTING -j openclash >/dev/null 2>&1
    iptables -t mangle -D PREROUTING -p udp -j openclash >/dev/null 2>&1
    iptables -t mangle -D PREROUTING -p tcp --dport 53 -j openclash_dns_hijack >/dev/null 2>&1
